name: DRIFT
options:
  bundleIdPrefix: com.tokyonasu
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  DRIFT:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: TechnoMaker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tokyonasu.Drift
        PRODUCT_NAME: DRIFT
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: DRIFT
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        DEVELOPMENT_TEAM: 83VGKGSQUH
        CODE_SIGN_STYLE: Automatic

