name: DRIFT
options:
  bundleIdPrefix: com.tokyonasu
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 12.0.0
targets:
  DRIFT:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: TechnoMaker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tokyonasu.Drift
        PRODUCT_NAME: DRIFT
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: TechnoMaker/Info.plist
        DEVELOPMENT_TEAM: 83VGKGSQUH
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: GoogleMobileAds
        product: GoogleMobileAds
